<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="apiregistration"
    errors="1" failures="0" hostname="" id="" package="apiregistration" skipped="0"
    tests="1" time="0.01100" timestamp="Wed, 08 Feb 2017 20:21:04 GMT">
  
    <testcase name="demoTest" time="0.01100" assertions="0">
    </testcase>
      <system-err>
          Error while running [Apiregistration / demoTest]:

  ReferenceError: name is not defined
    at Object.demoTest (E:\GITRepoAuto\QAAutomation\tests\apiregistration\apiregistration.js:7:19)
    at Module.call (C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\milind_deshpande\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
      </system-err>
  
  
  </testsuite>
</testsuites>
